### ISSUE TITLE
Type error is thrown

### ISSUE THREAD

**Issue by oldesec** [mandatoryprogrammer/TrustTrees#16]
Hi,

Command :  trusttrees.py --target example.com

The following error occurs.

```
Traceback (most recent call last):
  File "trusttrees.py", line 765, in <module>
    draw_graph_from_cache(target_hostname),
  File "trusttrees.py", line 530, in draw_graph_from_cache
    ns_result=ns_result,
  File "trusttrees.py", line 636, in get_graph_data_for_ns_result
    query_error['error'],
TypeError: cannot concatenate 'str' and 'tuple' objects
```

**Comment by KevinHock** [comment]
Whoops, I will look into  this immediately :D

**Comment by KevinHock** [comment]
Thanks a bunch for reporting this @oldesec 🤗  I fixed it in the above commit.

Let me know if you run into anything else 👍
