### ISSUE TITLE
TypeError When Running Against "cde.int"

### ISSUE THREAD

**Issue by mandatoryprogrammer** [mandatoryprogrammer/TrustTrees#31]
```
(env) mandatory@localhost:~/trusttrees$ trusttrees.py -t cde.int

      ______                __ ______
     /_  __/______  _______/ //_  __/_______  ___  _____
      / / / ___/ / / / ___/ __// / / ___/ _ \/ _ \/ ___/
     / / / /  / /_/ (__  ) /_ / / / /  /  __/  __(__  )
    /_/ /_/   \__,_/____/\__//_/ /_/   \___/\___/____/
              Graphing & Scanning DNS Delegation Trees

[ STATUS ] Querying nameserver '193.0.14.129/k.root-servers.net.' for NS of 'cde.int.'
[ STATUS ] Querying nameserver '199.43.135.53/x.iana-servers.net.' for NS of 'cde.int.'
[ STATUS ] Querying nameserver '91.121.219.90/s1.cleverway.eu.' for NS of 'cde.int.'
[ STATUS ] Querying nameserver '164.132.88.117/s2.cleverway.eu.' for NS of 'cde.int.'
[ STATUS ] Querying nameserver '199.43.133.53/y.iana-servers.net.' for NS of 'cde.int.'
[ STATUS ] Querying nameserver '199.43.134.53/z.iana-servers.net.' for NS of 'cde.int.'
[ STATUS ] Querying nameserver '137.39.1.3/ns.uu.net.' for NS of 'cde.int.'
[ STATUS ] Querying nameserver '193.63.94.20/ns0.ja.net.' for NS of 'cde.int.'
[ STATUS ] Querying nameserver '193.0.9.4/sec2.authdns.ripe.net.' for NS of 'cde.int.'
[ STATUS ] Building 'cde.int.|ns|193.63.94.20|ns0.ja.net.'...
Traceback (most recent call last):
  File "/home/mandatory/trusttrees/env/bin/trusttrees.py", line 758, in <module>
    draw_graph_from_cache(target_hostname),
  File "/home/mandatory/trusttrees/env/bin/trusttrees.py", line 523, in draw_graph_from_cache
    ns_result=ns_result,
  File "/home/mandatory/trusttrees/env/bin/trusttrees.py", line 629, in get_graph_data_for_ns_result
    query_error['error'],
TypeError: cannot concatenate 'str' and 'tuple' objects
```

**Comment by KevinHock** [comment]
I’ll hopefully have this fixed and new version bumped by EOD 👍

**Comment by KevinHock** [comment]
Turns out I just need to bump the version, will do around 11am PST tomorrow.

Short-term fix is to install from source via ‘pip install -e .’

**Comment by mandatoryprogrammer** [comment]
Awesome thanks!

**Comment by KevinHock** [comment]
Okay this should be fixed 👍 -- Sorry about that

https://pypi.org/project/TrustTrees/ has the latest, it works on Python 3.
