### ISSUE TITLE
Can't open the generated graph(s) with --open

### ISSUE THREAD

**Issue by dgzlopes** [mandatoryprogrammer/TrustTrees#33]
**Description**
I get a `FileNotFoundError` exception when I run the default example from the [README.md](https://github.com/mandatoryprogrammer/TrustTrees#example-usage). Without `--open` TrustTrees works as expected.

**Environment** 
- TrustTrees version: 
  - v3.0.0
- pyenv local:
  - 3.7.0
- OS:
```
$ lsb_release -a
LSB Version:	core-11.0.1ubuntu1-noarch:security-11.0.1ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
```
**Output**

```
$ trusttrees --target example.com --open

      ______                __ ______
     /_  __/______  _______/ //_  __/_______  ___  _____
      / / / ___/ / / / ___/ __// / / ___/ _ \/ _ \/ ___/
     / / / /  / /_/ (__  ) /_ / / / /  /  __/  __(__  )
    /_/ /_/   \__,_/____/\__//_/ /_/   \___/\___/____/
              Graphing & Scanning DNS Delegation Trees
    
[ STATUS ] Querying nameserver '192.203.230.10/e.root-servers.net.' for NS of 'example.com.'
......
[ STATUS ] Opening final graph...
Traceback (most recent call last):
  File "/home/dgzlopes/.pyenv/versions/3.7.0/bin/trusttrees", line 11, in <module>
    load_entry_point('TrustTrees', 'console_scripts', 'trusttrees')()
  File "/home/dgzlopes/TrustTrees/trusttrees/__main__.py", line 43, in main
    args.upload_args,
  File "/home/dgzlopes/TrustTrees/trusttrees/draw.py", line 170, in generate_graph
    subprocess.call(['open', filename])
  File "/home/dgzlopes/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 304, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/dgzlopes/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/home/dgzlopes/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'open': 'open'
```

**Comment by KevinHock** [comment]
Thanks so much for making this @dgzlopes!

**Comment by KevinHock** [comment]
Fixed, thanks again! :)
